<div class="row">
    <section class="col-md-push-4 col-lg-4 text-center">
        <figure>
            <img height="40%" width="40%" src="<?php echo  $this->baseUrl('/img/namibiaca.gif'); ?>" />
        </figure>
    </section>    
</div>

<div class="row">
    <section class="col-md-push-4 col-lg-4">
        <?php
            if (!empty($this->message)) {
                    echo '<font color="red">';
                    echo $this->escape($this->message[0]);
                    echo '</font>';
            }

            $this->form->setName('login')
                       ->setAction('/index/login')
                       ->setMethod('post'); 
            echo $this->form; 
            ?>
    </section>    
</div>
  