<section>
    <div class="row">
        <div class="col-lg-push-3 col-md-6">
            <div class="panel panel-danger">
                <div class="access-denied panel-heading">
                        <h1 class="panel-title text-danger"><i class="fa fa-ban"></i> Access Denied</h1>
                </div>
                <div class="panel-body" id="access-denied">
                    <p>
                        You are not allowed to access the requested resource.
                        Please choose one of the following options.
                    </p>
                    <ul>
                        <li>Sign out and Sign In again as a different user.</li>
                        <li>Contact your administrator if you think you should be allowed to access this BSSP resource.</li>
                    </ul>
                    
                    <p>
                      Thank you.  
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>