<section>
    <div class="row">
        <div class="col-lg-push-3 col-md-6">
            <div class="panel panel-danger">
                <div class="access-denied panel-heading">
                        <h1 class="panel-title text-danger"><i class="fa fa-e"></i> Parameters Missing Error</h1>
                </div>
                <div class="panel-body" id="access-denied">
                    <p>
                        The system has noticed that some critical parameters are missing.
                        Because of that the system will not be able to complete your request.
                    </p>
                    <ul>
                        <li>Please go back using the menu above and try again afresh.</li>
                        <li>Contact your administrator with information/details that led to this problem.</li>
                    </ul>                    
                    <p>
                      Thank you.  
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>