<section class="row">
    <div class="col-lg-12">
        <?php echo $this->partial('/partials/new-user.phtml',[]) ?>
    </div>
</section>

<section>
      <?php if(count($this->paginator) > 0): ?>
      <div class="table">
    <div class="row header blue">
      <div class="cell">
        First Name
      </div>
      <div class="cell">
        Last Name
      </div>
      <div class="cell">
        E-mail Address
      </div>
      <div class="cell">
        Role
      </div>
      <div class="cell"></div>         
    </div>
                            <?php $count = 1 ; foreach ($this->paginator as $entityOnject): ?>

                <div class="row">
                  <div class="cell">
                    <span class="text-info"><?php echo $this->escape($count) ?></span>  : <?php echo $this->escape($entityOnject['firstname']) ?>
                  </div>
                  <div class="cell">
                    <?php echo $this->escape($entityOnject['lastname']) ?>
                  </div>
                  <div class="cell">
                    <?php echo $this->escape($entityOnject['email']) ?>
                  </div>
                  <div class="cell">
                    <?php echo $this->escape($entityOnject['role_description']) ?>
                  </div>
                    <div class="cell action text-right">
                                            <?php if(1 === intval($entityOnject['userId'])): ?>

                                            <?php else: ?>
                                        
                                                    <a href="<?php echo $this->escape($this->url(array('module'=>'users','controller' => 'index', 'action' => 'status' , 'id'=> $this->escape($entityOnject['userId'])), null, true)) ?>">
                                                      Disable User
                                                    </a>                    
                                                    <a href="<?php echo $this->escape($this->url(array('module'=>'users','controller' => 'create', 'action' => 'delete' , 'id'=> $this->escape($entityOnject['userId'])), null, true)) ?>">
                                                      Remove User
                                                    </a>
                                                    <a href="<?php echo $this->escape($this->url(array('module'=>'users','controller' => 'update', 'action' => 'index' , 'id'=> $this->escape($entityOnject['userId'])), null, true)) ?>">
                                                        Edit User
                                                    </a>                                          

                                            <?php endif; ?> 
                    </div>                   
                </div>                               
                    <?php $count++; endforeach; ?> 
            </div>    
                    <?php else: ?>
                        <section class="row">
                            <div class="col-lg-12">
                                <p class="text-info info">
                                    There are no users records in the BSSP system at the moment, please use the "create new user" link on the right to create records .
                                </p>
                            </div>
                        </section>                            
                    <?php endif; ?>       

</section>
<section class="row">
    <div class="col-lg-12">
        <?php echo $this->partial('/partials/new-user.phtml',[]) ?>
    </div>
</section>
<section>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', ['partials/pagination.phtml' , 'service']); ?>
</section>