<form class="search-form" method="post" action="/search/projects/">
<section>
<?php if(count($this->paginator) > 0): ?>
    <div class="table">
    <div class="row header blue">
      <div class="cell">
        Project Number
      </div>
      <div class="cell">
        Project Name
      </div>
      <div class="cell">
        Amount Committed
      </div>
      <div class="cell">
        Amount Paid
      </div>
      <div class="cell">
        Amount Outstanding
      </div>
      <div class="cell">
        
      </div>         
    </div>
    <div class="row search-row">
        
            <div class="cell">
              <?php echo $this->form->projectNumber ?>
            </div>
            <div class="cell">
              <?php echo $this->form->projectName ?>
            </div>       
            <div class="cell ">
            </div>
            <div class="cell ">
            </div>
            <div class="cell ">

            </div>        
            <div class="cell action text-right">
                <button class="btn btn-block btn-success" type="submit" id="btnSubmit" name="btnSubmit"><i class="fa fa-search"></i> Search</button>
            </div>
        
    </div>         

     

                            <?php $count = 1 ; foreach ($this->paginator as $entityOnject): ?>

                <div class="row">
                    <div class="cell">
                      <span class="text-info"><?php echo $this->escape($count) ?></span>  : <?php echo $this->escape($entityOnject['number']) ?>
                    </div>
                    <div class="cell">
                      <?php echo $this->escape($entityOnject['name']) ?>
                    </div>
                    <div class="cell">
                      $ <?php echo $this->escape($entityOnject['bugdet']['budgetAmount']) ?>
                    </div>
                    <div class="cell">
                      $ <?php echo $this->escape($entityOnject['bugdet']['paidAmount']) ?>
                    </div>
                    <div class="cell">
                      $ <?php echo $this->escape($entityOnject['bugdet']['autstandingAmount']) ?>
                    </div>
                    <div class="cell action text-right">
                                            <?php if( 'Y' === $entityOnject['isDisscussed']): ?>

                                                  <a class="text-info" href="<?php echo $this->escape($this->url(array('module'=>'projects','controller' => 'composition', 'action' => 'update' , 'pn'=> $this->escape($entityOnject['number'])), null, true)) ?>" >
                                                    Edit Project Details
                                                  </a>     

                                            <?php else:?>                
                                                  <a href="<?php echo $this->escape($this->url(array('module'=>'projects','controller' => 'composition', 'action' => 'index' , 'pn'=> $this->escape($entityOnject['number'])), null, true)) ?>">
                                                      Add Project Details
                                                  </a>             
                                            <?php endif;?>
                    </div>                   
                </div>                               
                    <?php $count++; endforeach; ?>
  </div>        
                    <?php else: ?>
                        <section class="row">
                            <div class="info-wrap">
                                <p class="text-info info">
                                    There are no projects records in the BSSP system at the moment.
                                </p>
                            </div>
                        </section>                            
                    <?php endif; ?>       
    
</section>
<section>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', ['partials/pagination.phtml' , 'service']); ?>
</section>
</form>