<section>
          <div id="request-accordion" class="accordion">
            <h3 class="expand">Request Details</h3>
            <div class="collapse shown">
                <ul>
                    <li><span class="text-thick">Request Number</span> : <?php echo $this->escape($this->request['requestNumber']) ?></li>
                    <li><span class="text-thick">Request Type</span> : <?php echo $this->escape($this->request['requestType']) ?></li>
                            <?php if('Other' === $this->escape($this->request['requestType'])): ?>
                                <li>
                                    <span class="text-thick text-warning">Other Request Type Text</span> : <?php echo $this->escape($this->request['otherRequestTypeText']); ?>
                                </li>                                        
                            <?php endif;?>       
                    <li><span class="text-thick">Request Priority Area</span> : <?php echo $this->escape($this->request['requestPriotityArea']) ?></li>
                    <li><span class="text-thick">Request Business Activity</span> : <?php echo $this->escape($this->request['requestBusinessActivity']) ?></li>
                    <li class="status-<?php echo strtolower($this->escape($this->request['requestStatus'])) ?>">Request Status : <?php echo $this->escape($this->request['requestStatus']) ?></li>
                </ul>
            </div>
            <h3 class="expand">Application Details</h3>
            <div class="collapse">
                <ul>
                    <li><span class="text-thick">Application Number</span> : <?php echo $this->escape($this->application['applicationNumber']) ?></li>
                    <li><span class="text-thick">Application Date</span> : <?php echo $this->escape($this->application['applicationDate']) ?></li>
                    <li><span class="text-thick">Application Acknowledgement Date</span> : <?php echo $this->escape($this->application['applicationAcknowledgementDate']) ?></li>
                </ul>
            </div>
            <h3 class="expand">Applicant Details</h3>
            <div class="collapse">
                <ul>
                        <?php if('company' === $this->escape($this->application['entityType'])): ?>
                            <li><span class="text-thick">Company Name</span> : <?php echo $this->escape($this->application['companyName']) ?></li>
                            <li><span class="text-thick">Company Registration Name</span> : <?php echo $this->escape($this->application['companyRegistrationNumber']) ?></li>                                                                                       
                        <?php else: ?>
                            <li><span class="text-thick">First Name</span> : <?php echo $this->escape($this->application['firstName']) ?></li>
                            <li><span class="text-thick">Middle Name</span> : <?php echo $this->escape($this->application['middleName']) ?></li>
                            <li><span class="text-thick">Last Name</span> : <?php echo $this->escape($this->application['lastName']) ?></li>                            
                            <li><span class="text-thick">Date of Birth</span> : <?php echo $this->escape($this->application['dateOfBirth']) ?></li>
                            <li><span class="text-thick">Identity Number</span> : <?php echo $this->escape($this->application['identityNumber']) ?></li>
                            <li><span class="text-thick">Passport Number</span> : <?php echo $this->escape($this->application['passportNumber']) ?></li>                
                        <?php endif; ?>                     

                    <li>
                            <div class="table">
                              <div class="row header blue">
                                <div class="cell">
                                  Telephone Number
                                </div>
                                <div class="cell">
                                  Mobile Number
                                </div>
                                <div class="cell">
                                  Fax Number
                                </div>
                                <div class="cell">
                                  E-mail Address
                                </div>      
                            </div>
                            <div class="row">
                                <div class="cell">
                                  <?php echo $this->escape($this->application['telephoneNumber']) ?>
                                </div>
                                <div class="cell">
                                  <?php echo $this->escape($this->application['mobileNumber']) ?>
                                </div>
                                <div class="cell">
                                  <?php echo $this->escape($this->application['faxNumber']) ?>
                                </div>
                                <div class="cell">
                                  <?php echo $this->escape($this->application['emailAddress']) ?>
                                </div>                 
                              </div>                                                            
                            </div>                         
                    </li>
                </ul>
            </div>            
            <h3 class="expand">Request Resolution Details</h3>
            <div class="collapse">
                <ul>
                    <li><span class="text-thick">Resolution Date</span> : <?php echo $this->escape($this->resolution['resolutionDiscussionDate']) ?></li>
                    <li class="status-<?php echo strtolower($this->escape($this->request['requestStatus'])) ?>"><span class="text-thick">Resolution Status</span> : <?php echo $this->escape($this->resolution['resolutionDiscussionStatus']) ?></li>
                    <li><span class="text-thick">Resolution Correspondence Date</span> : <?php echo $this->escape($this->resolution['resolutionCorespondenceDate']) ?></li>
                    <li class=""><span class="text-thick">Resolution Remarks</span> : <?php echo $this->escape($this->resolution['resolutionRemarks']) ?></li>
                    <li class=""><span class="text-thick">Resolution Remarks Description</span> : <?php echo $this->escape($this->resolution['resolutionRemarksDescription']) ?></li>
                </ul>
            </div>
                    <?php if('APPROVED' === $this->escape($this->request['requestStatus'])): ?>
                        <h3 class="expand">Project Details</h3>
                        <div class="collapse">
                            <ul>
                                <li><span class="text-thick">Project Number</span> : <?php echo $this->escape($this->project['number']) ?></li>
                                <li><span class="text-thick">Project Name</span> : <?php echo $this->escape($this->project['name']) ?></li>
                                <li><span class="text-thick">Project Commencement Date</span> : <?php echo $this->escape($this->project['startDate']) ?></li>
                                <li><span class="text-thick">Project Completion Date</span> : <?php echo $this->escape($this->project['endDate']) ?></li>
                                <li><span class="text-thick">Project Status</span> : <?php echo $this->escape($this->project['status']) ?></li>
                            </ul>
                        </div> 
                    <?php endif; ?>                        
          </div>
</section>                            