<div id="header" class="text-left">
    <article class="row">
        <section class="col-lg-8">
            <h1 class="logo-link"><a href="/">BSSP<span class="fade">manager</span> v1 - RC-02</a></h1>
            <p id="slogan">The Business Support Services Progamme’s (BSSP)</p>            
        </section>
        <section class="col-lg-4">
            <p id="profile" class="text-right profile"><?php echo $this->ProfileLink(); ?></p>
        </section>
    </article>        
</div>