<form class="search-form" method="post" action="/search/consultants/">
<section>

<div class="table">
    <div class="row header blue">
      <div class="cell">
        Project Consultant Name
      </div>
            <div class="cell"></div>
            <div class="cell"></div>
            <div class="cell"></div>
            <div class="cell"></div>             
            <div class="cell"></div>         
    </div>
    <div class="row search-row">
        
            <div class="cell">
              <?php echo $this->form->legalEntityName ?>
                <?php echo $this->form->entityCategory ?>
            </div>
            <div class="cell action text-right">
                <button class="btn btn-block btn-success" type="submit" id="btnSubmit" name="btnSubmit"><i class="fa fa-search"></i> Search</button>
            </div>        
            <div class="cell"></div>
            <div class="cell"></div>         
            <div class="cell"></div>
            <div class="cell"></div>        
        
    </div>
<?php if(count($this->paginator) > 0): ?>    
        <?php $count = 1 ; foreach ($this->paginator as $entityOnject): ?>

                <div class="row">
                    <div class="cell">
                        <?php echo $this->escape($count) ?>  : <?php echo $this->escape($entityOnject['legalEntityName']) ?>
                    </div>
            <div class="cell"></div>
            <div class="cell"></div>
            <div class="cell"></div>
            <div class="cell"></div>             
                    <div class="cell action text-right">
                        <a href="<?php echo $this->escape($this->url(array('module'=>'consultants','controller' => 'create', 'action' => 'delete' , 'id'=> $this->escape($entityOnject['id'])), null, true)) ?>" onclick="Docs.expandOperationsForResource('pet'); return false;">
                          Remove Consultant
                        </a>
                        <a href="<?php echo $this->escape($this->url(array('module'=>'consultants','controller' => 'update', 'action' => 'index' , 'id'=> $this->escape($entityOnject['id'])), null, true)) ?>">Edit Consultant</a>                        
                    </div>                   
                </div>                               
        <?php $count++; endforeach; ?>
  </div>
    </section>  
        <?php else: ?>
  </div>
    </section>    
                    <section class="row">
                            <div class="info-wrap">
                                <p class="text-info info">
                                    There are no project consultants records in the BSSP system to match your search criteria.Please change the search criteria and try again.
                                </p>
                            </div>
                    </section>
        <?php endif; ?>          
               
<section>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', ['partials/pagination.phtml' , 'service']); ?>
</section>
</form>