<?php echo $this->doctype(); ?>

<html lang="en" dir="ltr">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ///exit('default layout');?>
<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/bootstrap/css/bootstrap.min.css') ?>" type="text/css" media="all">
   
<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/jquery/ui/1.11/jquery-ui.min.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/validator/validator.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/style.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/notification/notification.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/font-awesome/css/font-awesome.min.css') ?>" type="text/css" media="all">


<script src="<?php echo  $this->baseUrl('libs/jquery/2.1.1/jquery.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.11/jquery.ui.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/validation/jquery.validate.min'); ?>"></script>

<!--  Style -->
<script src="<?php echo  $this->baseUrl('js/login.js'); ?>"></script>

<!-- .......... -->
<!--[if lt IE 9]>
<link rel="stylesheet" href="styles/ie.css" type="text/css" media="all">
<script src="scripts/ie/css3-mediaqueries.min.js"></script>
<script src="scripts/ie/ie9.js"></script>
<script src="scripts/ie/html5shiv.min.js"></script>
<![endif]-->
   <?php $this->headLink()
                          ->appendStylesheet($this->baseUrl('/css/bssp.co.css'));?>
    <?php echo $this->navigation()->links(); ?>
   <?php echo $this->headLink(); ?>
   <?php echo $this->headScript(); ?>
<style>
    td{
        padding: 2px 4px;
    }
</style>
</head>
<body class="auction" onload="">
<div id="wrap" class="container">
    <!-- Header Contents -->
<?php //echo $this->render('app-header.phtml'); ?>
    <section class="row">

    </section>
    <section class="breadcrumb login">
            <hgroup class="hg">

            </hgroup>        
    </section>        
    </div>
<div class="container">
    <!-- Main Contents -->    
        <section class="row">
            <section class="col-lg-12">
                <?php echo $this->flashMessages(); ?>
            </section>
            <section class="row">
                                   <!-- Content -->
                            <?php echo $this->layout()->content; ?>
            </section>       

        </section>
</div>
    <!-- Footer Contents -->    
    <footer>
        <section id="" class="container">
        </section>        
    </footer>   
 <!--
 Script COntainer
 -->

<script src="<?php echo  $this->baseUrl('js/app-validation.js'); ?>"></script>
</body>
</html>