<form class="search-form" method="post" action="/search/consultants/">
<?php echo $this->partial('/partials/new-consultant.phtml',[]) ?>
<section>
<?php if(count($this->paginator) > 0): ?>
<div class="table">
    <div class="row header blue">
            <div class="cell">
              Project Consultant Name
            </div>
            <div class="cell">Committed Amount(N$)</div>
            <div class="cell">Paid Amount(N$)</div>
            <div class="cell"></div>
            <div class="cell"></div>             
            <div class="cell"></div>         
    </div>
    <div class="row search-row">
        
            <div class="cell">
              <?php echo $this->form->legalEntityName ?>
                <?php echo $this->form->entityCategory ?>
            </div>
            <div class="cell action text-right">
                <button class="btn btn-block btn-success" type="submit" id="btnSubmit" name="btnSubmit"><i class="fa fa-search"></i> Search</button>
            </div>        
            <div class="cell"></div>
            <div class="cell"></div>         
            <div class="cell"></div>
            <div class="cell"></div>        
        
    </div>     
        <?php $count = 1 ; foreach ($this->paginator as $entityOnject): ?>
        <?php $budgetData = Budgets_Model_ProjectBudgetMapper::fetchConsultanceBudgetByConultantLegalEntityId($entityOnject['id']);    // Zend_Debug::dump($budgetData); ?>
                <div class="row">
                    <div class="cell">
                        <?php echo $this->escape($count) ?>  : <?php echo $this->escape($entityOnject['legalEntityName']) ?>
                    </div>
            <div class="cell"><?php echo $this->escape($budgetData['committedAmount']) ?></div>
            <div class="cell"><?php echo $this->escape($budgetData['paidAmount']) ?></div>
            <div class="cell"></div>
            <div class="cell"></div>             
                    <div class="cell action text-right">
                        <a href="<?php echo $this->escape($this->url(array('module'=>'consultants','controller' => 'update', 'action' => 'index' , 'id'=> $this->escape($entityOnject['id'])), null, true)) ?>">Edit Consultant</a>                        
                    </div>                   
                </div>                               
        <?php $count++; endforeach; ?>
  </div>
</section> 
        <?php else: ?>
                    <section class="row">
                        <div class="info-wrap">
                            <p class="text-info info">
                                There are no consultants records in the BSSP system at the moment, please use the "create new consultant" link on the right to create records .
                            </p>
                        </div>
                    </section>
        <?php endif; ?>          
                
            <?php echo $this->partial('/partials/new-consultant.phtml',[]) ?>
<section>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', ['partials/pagination.phtml' , 'service']); ?>
</section>
</form>