<div class="row">
    <section class="col-md-push-4 col-lg-4 text-center">
        <figure>
            <img height="40%" width="40%" src="<?php echo  $this->baseUrl('/img/namibiaca.gif'); ?>" />
        </figure>
    </section>    
</div>

<div class="row">
    <section class="col-md-push-4 col-lg-4">
        <?php
            $this->form->setName('login')
                       ->setAction('/login/index/login')
                       ->setMethod('post'); 
            echo $this->form; 
            ?>
    </section>    
</div>
<div class="row">
    <section class="col-md-push-4 col-lg-4">     
    </section>    
</div>